theme: jekyll-theme-minimal


logo: /img/photo.jpg

title: Masahiro MIZUKAMI - Personal Page
description: Masahiro MIZUKAMI is a researcher, interested in Chat-Oriented Dialogue System and Individuality Modeling (Linguistic, Dialogic).
