theme: jekyll-theme-minimal
title: Masahiro MIZUKAMI - Personal Page
logo: /img/photo.jpg
description: Masahiro MIZUKAMI is a researcher, interested in Chat-Oriented Dialogue System and Individuality Modeling (Linguistic, Dialogic).
