# theme setting
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
remote_theme: pages-themes/primer

# page setting
lang: ja
title: 'Masahiro Mizukami .github.io'
email: 'ma.aqua.13 (at) gmail.com'
twitter_username: 'mima_tea'
github_username: 'masahiro-mi'
description: I'm a researcher, interested in Dialogue Systems and Individuality Modeling.



#TOC
toc:
  - title: Group 1
    subfolderitems:
      - page: Thing 1
        url: /thing1.html
      - page: Thing 2
        url: /thing2.html
      - page: Thing 3
        url: /thing3.html
  - title: Group 2
    subfolderitems:
      - page: Piece 1
        url: /piece1.html
      - page: Piece 2
        url: /piece2.html
      - page: Piece 3
        url: /piece3.html
  - title: Group 3
    subfolderitems:
      - page: Widget 1
        url: /widget1.html
      - page: Widget 2
        url: /widget2.html
      - page: Widget 3
        url: /widget3.html