theme: jekyll-theme-minimal
title: Masahiro MIZUKAMI - Personal Page
logo: /img/photo.jpg
description: Masahiro MIZUKAMI is a researcher, interested in Chat-Oriented Dialogue System and Individuality Modeling (Linguistic, Dialogic).
markdown: CommonMarkGhPages



main:
  - title: "HOME"
    url: index.html
  - title: "Posts"
    url: /year-archive/
  - title: "Categories"
    url: /categories/
  - title: "Tags"
    url: /tags/
  - title: "Pages"
    url: /page-archive/
  - title: "Collections"
    url: /collection-archive/
  - title: "External Link"
    url: https://google.com
