# theme setting
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
# remote_theme: pages-themes/primer
exclude:
  - node_modules
  - script

sass:
  style: :compressed

theme: jekyll-theme-primer

# page setting
lang: ja
title: 'Masahiro Mizukami .github.io'
email: 'ma.aqua.13 (at) gmail.com'
twitter_username: 'mima_tea'
github_username: 'masahiro-mi'
description: I'm a researcher, interested in Dialogue Systems and Individuality Modeling.